<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Supplier;
use Illuminate\Support\Facades\Hash;

class SupplierSeeder extends Seeder
{
    public function run()
    {
        $suppliers = [
            [
                'company_name' => 'Alpha Windows Pty Ltd',
                'abn' => '12345678901',
                'website' => 'https://alphawindows.com.au',
                'company_description' => 'Premium aluminium window manufacturer with 20 years experience.',
                'established_date' => '2003-01-15',
                'first_name' => 'John',
                'last_name' => 'Smith',
                'position' => 'General Manager',
                'email' => 'supplier1@example.com',
                'phone' => '0412345678',
                'password' => Hash::make('password'),
                'street_number' => '123',
                'street_name' => 'Industrial',
                'street_type' => 'Drive',
                'suburb' => 'Melbourne',
                'state' => 'VIC',
                'postcode' => '3000',
                'specialty_areas' => ['Aluminium Frames'],
                'minimum_order_value' => 5000.00,
                'lead_time_days' => 14,
                'is_active' => true,
                'is_verified' => true,
                'onboarding_status' => 'approved',
            ],
            [
                'company_name' => 'Beta Plastics Manufacturing',
                'abn' => '23456789012',
                'website' => 'https://betaplastics.com.au',
                'company_description' => 'Innovative plastic window frame solutions for modern homes.',
                'established_date' => '2010-06-20',
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'position' => 'Sales Director',
                'email' => 'supplier2@example.com',
                'phone' => '0423456789',
                'password' => Hash::make('password'),
                'street_number' => '456',
                'street_name' => 'Manufacturing',
                'street_type' => 'Street',
                'suburb' => 'Sydney',
                'state' => 'NSW',
                'postcode' => '2000',
                'specialty_areas' => ['Plastic Frames'],
                'minimum_order_value' => 3000.00,
                'lead_time_days' => 10,
                'is_active' => true,
                'is_verified' => true,
                'onboarding_status' => 'approved',
            ],
            [
                'company_name' => 'Gamma Window Solutions',
                'abn' => '34567890123',
                'website' => 'https://gammawindows.com.au',
                'company_description' => 'Specialist in both aluminium and plastic window systems.',
                'established_date' => '2015-03-10',
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'position' => 'Operations Manager',
                'email' => 'supplier3@example.com',
                'phone' => '0434567890',
                'password' => Hash::make('password'),
                'street_number' => '789',
                'street_name' => 'Business',
                'street_type' => 'Avenue',
                'suburb' => 'Brisbane',
                'state' => 'QLD',
                'postcode' => '4000',
                'specialty_areas' => ['Aluminium Frames', 'Plastic Frames'],
                'minimum_order_value' => 4000.00,
                'lead_time_days' => 12,
                'is_active' => true,
                'is_verified' => false,
                'onboarding_status' => 'under_review',
            ],
            [
                'company_name' => 'Delta Frame Works',
                'abn' => '45678901234',
                'website' => 'https://deltaframes.com.au',
                'company_description' => 'Quality aluminium frame manufacturer serving Perth market.',
                'established_date' => '2008-11-25',
                'first_name' => 'Lisa',
                'last_name' => 'Wilson',
                'position' => 'CEO',
                'email' => 'supplier4@example.com',
                'phone' => '0445678901',
                'password' => Hash::make('password'),
                'street_number' => '321',
                'street_name' => 'Enterprise',
                'street_type' => 'Court',
                'suburb' => 'Perth',
                'state' => 'WA',
                'postcode' => '6000',
                'specialty_areas' => ['Aluminium Frames'],
                'minimum_order_value' => 6000.00,
                'lead_time_days' => 16,
                'is_active' => true,
                'is_verified' => true,
                'onboarding_status' => 'approved',
            ],
            [
                'company_name' => 'Epsilon Plastic Systems',
                'abn' => '56789012345',
                'website' => 'https://epsilonplastic.com.au',
                'company_description' => 'Eco-friendly plastic window frame solutions.',
                'established_date' => '2020-02-14',
                'first_name' => 'David',
                'last_name' => 'Taylor',
                'position' => 'Founder',
                'email' => 'supplier5@example.com',
                'phone' => '0456789012',
                'password' => Hash::make('password'),
                'street_number' => '654',
                'street_name' => 'Innovation',
                'street_type' => 'Way',
                'suburb' => 'Adelaide',
                'state' => 'SA',
                'postcode' => '5000',
                'specialty_areas' => ['Plastic Frames'],
                'minimum_order_value' => 2500.00,
                'lead_time_days' => 8,
                'is_active' => true,
                'is_verified' => false,
                'onboarding_status' => 'pending',
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::updateOrCreate(
                ['email' => $supplier['email']],
                $supplier
            );
        }
    }
}